## Parameterized Deploy Template
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: techtrends-latest
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
          
          livenessProbe:
            httpGet:
              port: {{ .Values.livenessProbe.httpGet.port }}
              path: {{ .Values.livenessProbe.httpGet.path }}

          readinessProbe:
            httpGet:
              port: {{ .Values.readinessProbe.httpGet.port }}
              path: {{ .Values.readinessProbe.httpGet.path }}

        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
