## provide the name of the namespace
namespace:
  name: prod

## service details
service:
  port: 7111

## define the image to execute with the Deployment
image:
  pullPolicy: Always

## set the number of replicas for an application
replicaCount: 5

## setting up resource limits
resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m
