name: TechTrends - Package with Docker
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./project/techtrends/
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: {{Udacity_CNAA_Repo}}/techtrends:latest

